dist: xenial
language: python

branches:
  only:
  - master

env:
  - DEPS=""
  - DEPS="lxml"

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  # temporary workaround for numpy failing in virtualenv
  # https://github.com/travis-ci/travis-cookbooks/issues/48#issuecomment-10843018
  - export PYTHONIOENCODING=UTF8 # just in case
  - pip install numpy
  # only install deps if the $DEPS variable is not empty
  # -z returns true on empty string
  - if [[ ! -z "$DEPS" ]]; then pip install $DEPS; fi;
  - python setup.py install

script: python collada
